### ISSUE TITLE
Styling closer to native Obsidian UI

### ISSUE THREAD

**Issue by jancbeck** [Jambo2018/notion-assistant-plugin#13]
Hey, fantastic plugin! I wish it looked a bit more like the native UI so I made some tweaks:

https://github.com/Jambo2018/notion-assistant-plugin/assets/865311/0bb0c1fd-5853-42c7-b63f-08889216a77d

Feel free to use the CSS:

```css
#command-menu, #selection-menu .linemenu {
  font-size: 0.8em;
  -webkit-font-smoothing: antialiased;
  font-weight: 500;
  background-color: var(--color-base-20);
}

#command-menu .command-option,
#selection-menu .linemenu-option {
  padding: 6px 8px;
}
#command-menu .command-option:focus,
#selection-menu .linemenu-option:focus {
  background-color: var(--interactive-accent);
  color: var(--text-on-accent);
}
#command-menu .command-option div,
#selection-menu .linemenu-option div {
  padding: 4px;
  margin-right: 8px;
}
[commandtype="insert-heading4"] {
  border-bottom: 1px solid var(--background-modifier-border)
}
.command-option svg,
.linemenu-option svg {
  max-width: 12px;
  max-height: 12px;
}
#selection-menu .linemenu {
  transform: translateX(200px);
}
#selection-menu .selection-btn:hover {
  background-color: var(--interactive-accent);
  color: var(--text-on-accent);
}
#selection-menu .selection-btn:hover svg path {
  fill: white;
}
.selection-btn:first-child:hover::after {
  filter: brightness(0.5) invert(1);
}
/* Dropdown */
.selection-btn[commandtype="0"] {
  order: 9999;
}
/* Link */
.selection-btn[commandtype="1"] {
  order: 3;
}
/* Bold */
.selection-btn[commandtype="2"] {
  order: 1;
}
/* Strikethrough */
.selection-btn[commandtype="3"] {
  order: 0;
}
/* Italic */
.selection-btn[commandtype="4"] {
  order: 2;
}
/* Underline */
.selection-btn[commandtype="5"] {
  display: none;
}
/* Code */
.selection-btn[commandtype="6"] {
  order: 0;
}
/* Tex */
.selection-btn[commandtype="7"] {
  order: 0;
}
/* Higlight */
.selection-btn[commandtype="8"] {
  order: 0;
}
```
